---
- name: monitoring with swarm
  hosts: deploy
  roles:
    - {role: add_labels, tags: ["add_labels"]}
    - {role: cadvisor, tags: ["cadvisor"]}
    - {role: node_exporter, tags: ["node_exporter"]}
    - {role: prometheus, tags: ["prometheus"]}
    - {role: alertmanager, tags: ["alertmanager"]}
    - {role: grafana, tags: ["grafana"]}
