---
- name: Monitoring with swarm
  hosts: deploy
  roles:
    - {role: add_labels, tags: ["add_labels,deploy"]}
    - {role: cadvisor, tags: ["cadvisor,deploy"]}
    - {role: node_exporter, tags: ["node_exporter,deploy"]}
    - {role: prometheus, tags: ["prometheus,deploy"]}
    - {role: alertmanager, tags: ["alertmanager,deploy"]}
    - {role: grafana, tags: ["grafana,deploy"]}
    - {role: backup, tags: ["backup"]}
    - {role: recovery, tags: ["recovery"]}
    - {role: del_folder, tags: ["del_folder"]}
