---
- name: Remove service
  community.docker.docker_swarm_service:
    name: "{{ tag }}"
    state: absent

- name: Create a network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: configuration [{{ tag }}] preparation block
  become: true
  block:
    - name: "[{{ tag }}] Ensure folder exist"
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop:
        - {path: "{{ monitoring_folder }}/{{ tag }}", state: directory, mode: "775", owner: "{{ ansible_user }}", group: "{{ ansible_user }}"}

    - name: "[{{ tag }}] Upload  file"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
      loop:
        - {src: prometheus.yml, dest: "{{ monitoring_folder }}/{{ tag }}/prometheus.yml", mode: "664", owner: "{{ ansible_user }}", group: "{{ ansible_user }}"}

- name: Create config "{{ tag }}"
  community.docker.docker_config:
    name: "{{ item.name }}"
    data_src: "{{ item.data_src }}"
    state: "{{ item.state }}"
  loop:
    - {name: prometheus.yml, data_src: "{{ monitoring_folder }}/{{ tag }}/prometheus.yml", state: "{{ prometheus_state }}"}

- name: Create a volume
  community.docker.docker_volume:
    name: prometheus_data
    state: "{{ prometheus_state }}"

- name: deploy "{{ tag }}"
  community.docker.docker_swarm_service:
    name: "{{ tag }}"
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    state: "{{ prometheus_state }}"
    replicas: 1
    networks:
      - name: "{{ network_name }}"
    publish:
      - {mode: ingress, protocol: tcp, published_port: 9090, target_port: 9090}
    mounts:
      - source: prometheus_data
        target: /prometheus
        type: volume
    placement:
      constraints:
        - node.labels.key1 == monitoring
    configs:
    - config_name: "{{ item.name }}"
      filename: "{{ item.filename }}"
  loop:
    - {name: prometheus.yml, filename: "/etc/prometheus/prometheus.yml", state: "{{ prometheus_state }}"}
