---
name: GitHub-Actions-lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '<yaml_file_or_dir>'
          yamllint_strict: false
          yamllint_comment: true

#jobs:
#  lint:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Run a one-line script
#        uses: actions/checkout@v3

#      - name: Install the ansible-lint
#        run: apt-get install ansible-lint

#      - name: Install the yamllint
#        run: apt-get install yamllint

#      - name: Run the ansible-lint
#        run: ansible-lint
#        uses: ansible-community/ansible-lint-action@v6.0.2

#      - name: Run the yamllint
#        run: yamllint
#        uses: karancode/yamllint-github-action@master
