---
name: GitHub-Actions-lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
#      - name: Install community.docker
#        run: ansible-galaxy collection install community.docker
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: './.yamllint'
          yamllint_strict: false
          yamllint_comment: true

#      - name: Set up Python 3.9
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9 

#      - name: Install dependencies Including Ansible
#        run: |
#          python -m pip install --upgrade pip
#          pip install --no-cache-dir --upgrade pip && \
#          pip install --no-cache-dir ansible==6.3.0

#      - name: 'Ansible-lint'
#        uses: ansible/ansible-lint-action@v6.0.2
#        with:
#          targets: "./*.yml"
#          override-deps: |
#            ansible-lint==6.12.2
           
#      - name: Run ansible-lint
#        uses: ansible-community/ansible-lint-action@main
#        with:
#          args: "ansible"

 #     - name: Install dependencies Including Ansible
 #       run: |
 #         python -m pip install --upgrade pip
 #         pip install --no-cache-dir --upgrade pip && \
 #         pip install --no-cache-dir ansible==6.3.0 && \
 #        pip install --no-cache-dir yamllint==1.28.0 && \
 #         pip install --no-cache-dir ansible-lint==6.9.1
 #     - name: run ansible-lint
 #       run: |
 #         ansible-lint -x name,loop-var-prefix

#      - name: run syntax-check
#        run: |
#          ansible-playbook -i inventory/all.yml deploy.yml --syntax-check
#####################


        #with:
        #  path: "playbooks/"
#jobs:
#  lint:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Run a one-line script
#        uses: actions/checkout@v3

#      - name: Install the ansible-lint
#        run: apt-get install ansible-lint

#      - name: Install the yamllint
#        run: apt-get install yamllint

#      - name: Run the ansible-lint
#        run: ansible-lint
#        uses: ansible-community/ansible-lint-action@v6.0.2

#      - name: Run the yamllint
#        run: yamllint
#        uses: karancode/yamllint-github-action@master
