---
name: GitHub-Actions-lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
#      - name: Install community.docker
#        run: ansible-galaxy collection install community.docker
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: './.yamllint'
          yamllint_strict: false
          yamllint_comment: true

      - name: 'Ansible-lint'
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          targets: "./*.yml"
#          args: "ansible"
