---
name: Ansible Docker Swarm
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --upgrade pip && \
          pip install --no-cache-dir ansible==6.3.0 && \
          pip install --no-cache-dir yamllint==1.28.0 && \
          pip install --no-cache-dir ansible-lint==6.9.1
      - name: run ansible-lint
        run: |
          ansible-lint -x name,loop-var-prefix
      - name: run yamllint
        run: |
          yamllint -c lint.yaml .
      - name: run syntax-check
        run: |
          ansible-playbook -i inventory/all.yml deploy.yml --syntax-check
